apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: NodePort  # ✅ MUST be NodePort to use `nodePort`
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31019
      protocol: TCP
